export const books1 = [
    // Classic
    {
        id: 1,
        title: "Don Kishoti",
        author: "Miguel de Cervantes",
        category: "classic",
        image: "images/books/classic1.png",
        price: "1,200 ALL",
        rating: 4.8,
        description: "Një nga romanet më të famshme të letërsisë botërore, që ndjek aventurat e Don Kishotit dhe Sanço Panços.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 2,
        title: "Ana Karenina",
        author: "Lev Tolstoi",
        category: "classic",
        image: "images/books/classic2.png",
        price: "1,500 ALL",
        rating: 4.7,
        description: "Një roman klasik rreth dashurisë, tradhtisë dhe shoqërisë ruse.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 13,
        title: "Krim dhe Ndëshkim",
        author: "Fyodor Dostoevsky",
        category: "classic",
        image: "images/books/classic3.png",
        price: "1,300 ALL",
        rating: 4.9,
        description: "Një roman i thellë psikologjik mbi fajin, pendesën dhe shpëtimin.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 14,
        title: "Zonja Bovari",
        author: "Gustave Flaubert",
        category: "classic",
        image: "images/books/classic4.png",
        price: "1,400 ALL",
        rating: 4.6,
        description: "Historia tragjike e Emës, një grua që kërkon dashuri dhe kuptim përtej jetës së saj të zakonshme.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 15,
        title: "Krenari dhe paragjykim",
        author: "Jane Austen",
        category: "classic",
        image: "images/books/classic5.png",
        price: "1,100 ALL",
        rating: 4.9,
        description: "Një roman i njohur për humorin dhe vëzhgimin e hollë të shoqërisë angleze.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 16,
        title: "Uliksi",
        author: "James Joyce",
        category: "classic",
        image: "images/books/classic6.png",
        price: "1,600 ALL",
        rating: 4.5,
        description: "Një kryevepër moderniste që ndjek një ditë në jetën e Leopold Bloom në Dublin.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },

    // Modern
    {
        id: 3,
        title: "1984",
        author: "George Orwell",
        category: "modern",
        image: "images/books/modern1.jpg",
        price: "1,300 ALL",
        rating: 4.8,
        description: "Një distopi e shkruar në vitin 1949, që përshkruan një shoqëri të kontrolluar nga një regjim totalitar.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 4,
        title: "Getsbi i Madh",
        author: "F. Scott Fitzgerald",
        category: "modern",
        image: "images/books/modern2.jpg",
        price: "1,200 ALL",
        rating: 4.7,
        description: "Një roman për ëndrrën amerikane, dashurinë dhe humbjen në vitet 1920.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 17,
        title: "Njëqind Vjet Vetmi",
        author: "Gabriel García Márquez",
        category: "modern",
        image: "images/books/modern3.jpg",
        price: "1,400 ALL",
        rating: 4.9,
        description: "Saga magjike e familjes Buendía në qytetin imagjinar të Macondo.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 18,
        title: "Lolita",
        author: "Vladimir Nabokov",
        category: "modern",
        image: "images/books/modern4.jpg",
        price: "1,500 ALL",
        rating: 4.6,
        description: "Një thriller psikologjik rreth imoralitetit, obsesionit dhe abuzimit seksual. I rrëfyer nga narratori më pak i besueshëm që keni për të parë ndonjëherë.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 19,
        title: "Brave New World",
        author: "Aldous Huxley",
        category: "modern",
        image: "images/books/modern5.jpg",
        price: "1,300 ALL",
        rating: 4.7,
        description: "Një roman distopik që sfidon normat sociale dhe teknologjike, duke imagjinuar një botë ku lumturia kontrollohet përmes shkencës dhe manipulimit.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 20,
        title: "The Alchimist",
        author: "Paulo Coelho",
        category: "modern",
        image: "images/books/modern6.jpg",
        price: "1,200 ALL",
        rating: 4.8,
        description: "Një tregim frymëzues për një bari të ri që ndjek ëndrrën e tij për të gjetur një thesar të fshehur, duke zbuluar thesarët e brendshëm në udhëtim.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },

    // Children
    {
        id: 5,
        title: "Harry Potter dhe Guri Filozofal",
        author: "J.K. Rowling",
        category: "children",
        image: "images/books/children1.jpg",
        price: "1,800 ALL",
        rating: 4.9,
        description: "Fillimi magjik i një sage epike ku një djalë zbulon se është magjistar dhe nis aventurën e tij në shkollën Hogwarts.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 6,
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        category: "children",
        image: "images/books/children2.jpg",
        price: "1,600 ALL",
        rating: 4.8,
        description: "Një udhëtim epik i Bilbo Baggins me xhuxhët për të rifituar thesarin nga dragoi Smaug – një aventurë klasike fantastike.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 21,
        title: "Charlie dhe Fabrika e Çokollatës",
        category: "children",
        author: "Roald Dahl",
        image: "images/books/children3.jpg",
        price: "1,200 ALL",
        rating: 4.7,
        description: "Një djalë i varfër fiton një biletë të artë dhe viziton fabrikën e magjishme të çokollatës së Willy Wonka-s.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 22,
        title: "Matilda",
        author: "Roald Dahl",
        category: "children",
        image: "images/books/children4.jpg",
        price: "1,200 ALL",
        rating: 4.8,
        description: "Një vajzë e zgjuar me aftësi të jashtëzakonshme përballet me prindërit e saj të padrejtë dhe një drejtoreshë të ligë.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 23,
        title: "Artemis Fowl: Thesari i Popullit",
        author: "Eoin Colfer",
        category: "children",
        image: "images/books/children5.jpg",
        price: "800 ALL",
        rating: 4.6,
        description: "Një gjeni kriminel 12-vjeçar përballet me një botë sekrete të elfeve dhe teknologjisë së përparuar.",
        isbn: "978-99943-0-124-5",
        language: "Shqip"
    },
    {
        id: 24,
        title: "The Chronicles of Narnia vol. 1",
        category: "children",
        author: "C.S. Lewis",
        image: "images/books/children6.jpg",
        price: "700 ALL",
        rating: 4.7,
        description: "Katër fëmijë zbulojnë një botë magjike përmes një gardërobe dhe luftojnë për ta shpëtuar atë nga errësira.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },

    // Science

    {
        id: 7,
        title: "A Brief History of Time",
        author: "Stephen Hawking",
        category: "science",
        image: "images/books/science1.jpg",
        price: "1,900 ALL",
        rating: 4.8,
        description: "Një udhërrëfyes për universin që shpjegon konceptet komplekse të kozmologjisë për lexuesit e zakonshëm.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },
    {
        id: 8,
        title: "The Selfish Gene",
        author: "Richard Dawkins",
        category: "science",
        image: "images/books/science2.jpg",
        price: "1,800 ALL",
        rating: 4.7,
        description: "Një teori revolucionare që shpjegon evoluimin përmes perspektivës së gjeneve dhe përzgjedhjes natyrore.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },
    {
        id: 25,
        title: "Sapiens",
        author: "Yuval Noah Harari",
        category: "science",
        image: "images/books/science3.jpg",
        price: "2,000 ALL",
        rating: 4.9,
        description: "Një histori gjithëpërfshirëse e njerëzimit, nga Homo sapiens deri në botën moderne të inteligjencës artificiale.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },
    {
        id: 26,
        title: "IN SEARCH OF SCHRODINGER'S CAT",
        author: "John Gribbins",
        category: "science",
        image: "images/books/science4.jpg",
        price: "1,800 ALL",
        rating: 4.6,
        description: "Një eksplorim i teorisë kuantike dhe mistereve të saj përmes shembullit të famshëm të maces së Schrödinger-it.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },
    {
        id: 27,
        title: "Cosmos",
        author: "Dr. Becky Smethurst",
        category: "science",
        image: "images/books/science5.jpg",
        price: "1,900 ALL",
        rating: 4.8,
        description: "Një udhëtim i jashtëzakonshëm përmes universit me sqarime të thjeshta mbi yjet, galaktikat dhe më shumë.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },
    {
        id: 28,
        title: "ON THE ORIGIN OF TIME",
        author: "THOMAS HERTOG",
        category: "science",
        image: "images/books/science6.jpg",
        price: "2,100 ALL",
        rating: 4.7,
        description: "Një vështrim revolucionar mbi kohën dhe universin, bazuar në bashkëpunimin e autorit me Stephen Hawking.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },


    //best sellers
    {
        id: 9,
        title: "The Da Vinci Code",
        author: "Dan Brown",
        category: "best",
        image: "images/books/best1.jpg",
        price: "1,500 ALL",
        rating: 4.7,
        description: "Një thriller plot mistere që ndjek një profesor simbolike në një ndjekje për një sekret të fshehur nga Kisha Katolike.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },
    {
        id: 10,
        title: "The Handmaid's Tale",
        author: "Margaret Atwood",
        category: "best",
        image: "images/books/best2.jpg",
        price: "1,700 ALL",
        rating: 4.8,
        description: "Një tregim distopik për një shoqëri ku gratë trajtohen si pronë dhe rebelimi lind nga një shërbëtore.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },
    {
        id: 29,
        title: "The Kite Runner",
        author: "Khaled Hosseini",
        category: "best",
        image: "images/books/best3.jpg",
        price: "1,400 ALL",
        rating: 4.9,
        description: "Një histori prekëse për miqësinë, fajin dhe shpengimin në një Afganistan të trazuar.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },
    {
        id: 30,
        title: "The Book Thief",
        author: "Markus Zusak",
        category: "best",
        image: "images/books/best4.jpg",
        price: "1,500 ALL",
        rating: 4.8,
        description: "Një vajzë gjermane gjatë Luftës së Dytë Botërore gjen ngushëllim në libra ndërsa bota e saj shembet.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },
    {
        id: 31,
        title: "Life of Pi",
        author: "Yann Martel",
        category: "best",
        image: "images/books/best5.jpg",
        price: "1,400 ALL",
        rating: 4.7,
        description: "Një histori mbijetese dhe mrekullie për një djalë që lundron në det me një tigër bengalez pas një përmbytjeje.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },
    {
        id: 32,
        title: "The Help",
        author: "Kathryn Stockett",
        category: "best",
        image: "images/books/best6.jpg",
        price: "1,600 ALL",
        rating: 4.8,
        description: "Një roman i fuqishëm mbi marrëdhëniet racore dhe luftën për barazi në Amerikën e viteve '60.",
        isbn: "978-99943-0-124-5",
        language: "English"
    },

];

export const books = {
    1: {
        id: 1,
        title: "Don Kishoti",
        author: "Miguel de Cervantes",
        category: "classic",
        image: "images/books/classic1.png",
        price: "1,200 ALL",
        rating: 4.8,
        description: "Një nga romanet më të famshme të letërsisë botërore, që ndjek aventurat e Don Kishotit dhe Sanço Panços.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Botimet Toena",
        publicationYear: "2018",
        dimensions: "20 x 13 cm"
    },
    2: {
        id: 2,
        title: "Ana Karenina",
        author: "Lev Tolstoi",
        category: "classic",
        image: "images/books/classic2.png",
        price: "1,500 ALL",
        rating: 4.7,
        description: "Një roman klasik rreth dashurisë, tradhtisë dhe shoqërisë ruse.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Dituria",
        publicationYear: "2020",
        dimensions: "21 x 14 cm"
    },
    13: {
        id: 13,
        title: "Krim dhe Ndëshkim",
        author: "Fyodor Dostoevsky",
        category: "classic",
        image: "images/books/classic3.png",
        price: "1,300 ALL",
        rating: 4.9,
        description: "Një roman i thellë psikologjik mbi fajin, pendesën dhe shpëtimin.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Fan Noli",
        publicationYear: "2019",
        dimensions: "20 x 13 cm"
    },
    14: {
        id: 14,
        title: "Zonja Bovari",
        author: "Gustave Flaubert",
        category: "classic",
        image: "images/books/classic4.png",
        price: "1,400 ALL",
        rating: 4.6,
        description: "Historia tragjike e Emës, një grua që kërkon dashuri dhe kuptim përtej jetës së saj të zakonshme.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Pegi",
        publicationYear: "2017",
        dimensions: "19 x 12.5 cm"
    },
    15: {
        id: 15,
        title: "Krenari dhe paragjykim",
        author: "Jane Austen",
        category: "classic",
        image: "images/books/classic5.png",
        price: "1,100 ALL",
        rating: 4.9,
        description: "Një roman i njohur për humorin dhe vëzhgimin e hollë të shoqërisë angleze.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Uegen",
        publicationYear: "2021",
        dimensions: "20.5 x 13.5 cm"
    },
    16: {
        id: 16,
        title: "Uliksi",
        author: "James Joyce",
        category: "classic",
        image: "images/books/classic6.png",
        price: "1,600 ALL",
        rating: 4.5,
        description: "Një kryevepër moderniste që ndjek një ditë në jetën e Leopold Bloom në Dublin.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Onufri",
        publicationYear: "2016",
        dimensions: "22 x 15 cm"
    },
    3: {
        id: 3,
        title: "1984",
        author: "George Orwell",
        category: "modern",
        image: "images/books/modern1.jpg",
        price: "1,300 ALL",
        rating: 4.8,
        description: "Një distopi e shkruar në vitin 1949, që përshkruan një shoqëri të kontrolluar nga një regjim totalitar.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Onufri",
        publicationYear: "2017",
        dimensions: "21 x 14 cm"
    },
    4: {
        id: 4,
        title: "Getsbi i Madh",
        author: "F. Scott Fitzgerald",
        category: "modern",
        image: "images/books/modern2.jpg",
        price: "1,200 ALL",
        rating: 4.7,
        description: "Një roman për ëndrrën amerikane, dashurinë dhe humbjen në vitet 1920.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Dituria",
        publicationYear: "2018",
        dimensions: "20 x 13 cm"
    },
    17: {
        id: 17,
        title: "Njëqind Vjet Vetmi",
        author: "Gabriel García Márquez",
        category: "modern",
        image: "images/books/modern3.jpg",
        price: "1,400 ALL",
        rating: 4.9,
        description: "Saga magjike e familjes Buendía në qytetin imagjinar të Macondo.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Botimet Toena",
        publicationYear: "2019",
        dimensions: "22 x 15 cm"
    },
    18: {
        id: 18,
        title: "Lolita",
        author: "Vladimir Nabokov",
        category: "modern",
        image: "images/books/modern4.jpg",
        price: "1,500 ALL",
        rating: 4.6,
        description: "Një thriller psikologjik rreth imoralitetit, obsesionit dhe abuzimit seksual. I rrëfyer nga narratori më pak i besueshëm që keni për të parë ndonjëherë.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Pegi",
        publicationYear: "2020",
        dimensions: "21 x 14 cm"
    },
    19: {
        id: 19,
        title: "Brave New World",
        author: "Aldous Huxley",
        category: "modern",
        image: "images/books/modern5.jpg",
        price: "1,300 ALL",
        rating: 4.7,
        description: "Një roman distopik që sfidon normat sociale dhe teknologjike, duke imagjinuar një botë ku lumturia kontrollohet përmes shkencës dhe manipulimit.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Fan Noli",
        publicationYear: "2018",
        dimensions: "20 x 13 cm"
    },
    20: {
        id: 20,
        title: "The Alchimist",
        author: "Paulo Coelho",
        category: "modern",
        image: "images/books/modern6.jpg",
        price: "1,200 ALL",
        rating: 4.8,
        description: "Një tregim frymëzues për një bari të ri që ndjek ëndrrën e tij për të gjetur një thesar të fshehur, duke zbuluar thesarët e brendshëm në udhëtim.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Uegen",
        publicationYear: "2021",
        dimensions: "21.5 x 14 cm"
    },
    5: {
        id: 5,
        title: "Harry Potter dhe Guri Filozofal",
        author: "J.K. Rowling",
        category: "children",
        image: "images/books/children1.jpg",
        price: "1,800 ALL",
        rating: 4.9,
        description: "Fillimi magjik i një sage epike ku një djalë zbulon se është magjistar dhe nis aventurën e tij në shkollën Hogwarts.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Botimet Dituria",
        publicationYear: "2015",
        dimensions: "23 x 16 cm"
    },
    6: {
        id: 6,
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        category: "children",
        image: "images/books/children2.jpg",
        price: "1,600 ALL",
        rating: 4.8,
        description: "Një udhëtim epik i Bilbo Baggins me xhuxhët për të rifituar thesarin nga dragoi Smaug – një aventurë klasike fantastike.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Onufri",
        publicationYear: "2017",
        dimensions: "22 x 15 cm"
    },
    21: {
        id: 21,
        title: "Charlie dhe Fabrika e Çokollatës",
        author: "Roald Dahl",
        category: "children",
        image: "images/books/children3.jpg",
        price: "1,200 ALL",
        rating: 4.7,
        description: "Një djalë i varfër fiton një biletë të artë dhe viziton fabrikën e magjishme të çokollatës së Willy Wonka-s.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Pegi",
        publicationYear: "2018",
        dimensions: "21 x 14 cm"
    },
    22: {
        id: 22,
        title: "Matilda",
        author: "Roald Dahl",
        category: "children",
        image: "images/books/children4.jpg",
        price: "1,200 ALL",
        rating: 4.8,
        description: "Një vajzë e zgjuar me aftësi të jashtëzakonshme përballet me prindërit e saj të padrejtë dhe një drejtoreshë të ligë.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Botimet Toena",
        publicationYear: "2019",
        dimensions: "22 x 15 cm"
    },
    23: {
        id: 23,
        title: "Artemis Fowl: Thesari i Popullit",
        author: "Eoin Colfer",
        category: "children",
        image: "images/books/children5.jpg",
        price: "800 ALL",
        rating: 4.6,
        description: "Një gjeni kriminel 12-vjeçar përballet me një botë sekrete të elfeve dhe teknologjisë së përparuar.",
        isbn: "978-99943-0-124-5",
        language: "Shqip",
        publisher: "Dituria",
        publicationYear: "2016",
        dimensions: "21 x 14 cm"
    },
    24: {
        id: 24,
        title: "The Chronicles of Narnia vol. 1",
        author: "C.S. Lewis",
        category: "children",
        image: "images/books/children6.jpg",
        price: "700 ALL",
        rating: 4.7,
        description: "Katër fëmijë zbulojnë një botë magjike përmes një gardërobe dhe luftojnë për ta shpëtuar atë nga errësira.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "Botimet Toena",
        publicationYear: "2017",
        dimensions: "22 x 15 cm"
    },
    7: {
        id: 7,
        title: "A Brief History of Time",
        author: "Stephen Hawking",
        category: "science",
        image: "images/books/science1.jpg",
        price: "1,900 ALL",
        rating: 4.8,
        description: "Një udhërrëfyes për universin që shpjegon konceptet komplekse të kozmologjisë për lexuesit e zakonshëm.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "Bantam Books",
        publicationYear: "1988",
        dimensions: "24 x 16 cm"
    },
    8: {
        id: 8,
        title: "The Selfish Gene",
        author: "Richard Dawkins",
        category: "science",
        image: "images/books/science2.jpg",
        price: "1,800 ALL",
        rating: 4.7,
        description: "Një teori revolucionare që shpjegon evoluimin përmes perspektivës së gjeneve dhe përzgjedhjes natyrore.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "Oxford University Press",
        publicationYear: "1976",
        dimensions: "23 x 15 cm"
    },
    25: {
        id: 25,
        title: "Sapiens",
        author: "Yuval Noah Harari",
        category: "science",
        image: "images/books/science3.jpg",
        price: "2,000 ALL",
        rating: 4.9,
        description: "Një histori gjithëpërfshirëse e njerëzimit, nga Homo sapiens deri në botën moderne të inteligjencës artificiale.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "Harper",
        publicationYear: "2011",
        dimensions: "22 x 14 cm"
    },
    26: {
        id: 26,
        title: "IN SEARCH OF SCHRODINGER'S CAT",
        author: "John Gribbins",
        category: "science",
        image: "images/books/science4.jpg",
        price: "1,800 ALL",
        rating: 4.6,
        description: "Një eksplorim i teorisë kuantike dhe mistereve të saj përmes shembullit të famshëm të maces së Schrödinger-it.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "Phoenix Books",
        publicationYear: "1984",
        dimensions: "21 x 13 cm"
    },
    27: {
        id: 27,
        title: "Cosmos",
        author: "Dr. Becky Smethurst",
        category: "science",
        image: "images/books/science5.jpg",
        price: "1,900 ALL",
        rating: 4.8,
        description: "Një udhëtim i jashtëzakonshëm përmes universit me sqarime të thjeshta mbi yjet, galaktikat dhe më shumë.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "Picador",
        publicationYear: "2021",
        dimensions: "24 x 17 cm"
    },
    28: {
        id: 28,
        title: "ON THE ORIGIN OF TIME",
        author: "THOMAS HERTOG",
        category: "science",
        image: "images/books/science6.jpg",
        price: "2,100 ALL",
        rating: 4.7,
        description: "Një vështrim revolucionar mbi kohën dhe universin, bazuar në bashkëpunimin e autorit me Stephen Hawking.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "Cambridge University Press",
        publicationYear: "2022",
        dimensions: "23 x 16 cm"
    },
    9: {
        id: 9,
        title: "The Da Vinci Code",
        author: "Dan Brown",
        category: "best",
        image: "images/books/best1.jpg",
        price: "1,500 ALL",
        rating: 4.7,
        description: "Një thriller plot mistere që ndjek një profesor simbolike në një ndjekje për një sekret të fshehur nga Kisha Katolike.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "Doubleday",
        publicationYear: "2003",
        dimensions: "21 x 14 cm"
    },
    10: {
        id: 10,
        title: "The Handmaid's Tale",
        author: "Margaret Atwood",
        category: "best",
        image: "images/books/best2.jpg",
        price: "1,700 ALL",
        rating: 4.8,
        description: "Një tregim distopik për një shoqëri ku gratë trajtohen si pronë dhe rebelimi lind nga një shërbëtore.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "McClelland and Stewart",
        publicationYear: "1985",
        dimensions: "22 x 15 cm"
    },
    29: {
        id: 29,
        title: "The Kite Runner",
        author: "Khaled Hosseini",
        category: "best",
        image: "images/books/best3.jpg",
        price: "1,400 ALL",
        rating: 4.9,
        description: "Një histori prekëse për miqësinë, fajin dhe shpengimin në një Afganistan të trazuar.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "Riverhead Books",
        publicationYear: "2003",
        dimensions: "20 x 13 cm"
    },
    30: {
        id: 30,
        title: "The Book Thief",
        author: "Markus Zusak",
        category: "best",
        image: "images/books/best4.jpg",
        price: "1,500 ALL",
        rating: 4.8,
        description: "Një vajzë gjermane gjatë Luftës së Dytë Botërore gjen ngushëllim në libra ndërsa bota e saj shembet.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "Knopf Books",
        publicationYear: "2005",
        dimensions: "23 x 15 cm"
    },
    31: {
        id: 31,
        title: "Life of Pi",
        author: "Yann Martel",
        category: "best",
        image: "images/books/best5.jpg",
        price: "1,400 ALL",
        rating: 4.7,
        description: "Një histori mbijetese dhe mrekullie për një djalë që lundron në det me një tigër bengalez pas një përmbytjeje.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "Knopf Canada",
        publicationYear: "2001",
        dimensions: "21 x 14 cm"
    },
    32: {
        id: 32,
        title: "The Help",
        author: "Kathryn Stockett",
        category: "best",
        image: "images/books/best6.jpg",
        price: "1,600 ALL",
        rating: 4.8,
        description: "Një roman i fuqishëm mbi marrëdhëniet racore dhe luftën për barazi në Amerikën e viteve '60.",
        isbn: "978-99943-0-124-5",
        language: "English",
        publisher: "Amy Einhorn Books",
        publicationYear: "2009",
        dimensions: "22 x 15 cm"
    }

};
